<template>
  <section class="section solution">
    <div class="container">
      <div
        v-for="(step, idx) of steps"
        :key="`solution-${idx}`"
        class="step">
        <div class="columns is-mobile text--left is-lock-marged">
          <div class="column is-dots">
            <svg
              width="7px"
              height="76px"
              viewBox="0 0 7 76"
              xmlns="http://www.w3.org/2000/svg"
              xmlns:xlink="http://www.w3.org/1999/xlink">
              <g
                stroke="none"
                stroke-width="1"
                fill="none"
                fill-rule="evenodd">
                <g fill-rule="nonzero">
                  <path
                    d="M3.5,7 L3.5,72.5"
                    stroke="#464769" />
                  <circle
                    :fill="stepColor(idx, 0)"
                    cx="3.5"
                    cy="3.5"
                    r="3.5" />
                  <circle
                    :fill="stepColor(idx, 1)"
                    cx="3.5"
                    cy="26.5"
                    r="3.5" />
                  <circle
                    :fill="stepColor(idx, 2)"
                    cx="3.5"
                    cy="49.5"
                    r="3.5" />
                  <circle
                    :fill="stepColor(idx, 3)"
                    cx="3.5"
                    cy="72.5"
                    r="3.5" />
                </g>
              </g>
            </svg>
          </div>
          <div class="column is-full">
            <h2>{{ step > 0 ? 'Asyncy ' : '' }}<vue-typer
              :repeat="0"
              :text="step.name"
              class="dark" /></h2>
            <div class="separator" />
            <p
              class="solution-content"
              v-html="step.content" />
          </div>
        </div>
        <div class="rounded">
          <solution-svg :step="idx" />
        </div>
      </div>
    </div>
    <!-- <lock-room :steps="steps.length">
      <template slot-scope="{ step }">
      </template>
    </lock-room> -->
  </section>
</template>

<script>
import SolutionSvg from '@/components/Home/SolutionSvg'
import LockRoom from '@/components/LockRoom'

export default {
  name: 'SolutionLock',
  components: { LockRoom, SolutionSvg },
  data: () => ({
    steps: [{
      name: 'Meet Storyscript',
      content: 'The language for storytelling data that powers your application.<br>Storyscript strings together microservices, representing architecture as code. Fully-asynchronous, service-oriented programming that intuitively expresses data flow to rapidly develop applications in a production-grade environment.',
      img: '@/assets/img/storyscript-solution.svg'
    }, {
      name: 'Hub',
      content: 'The developer marketplace to build, share and discover <b>microservices</b>.<br>Anonymous metrics and tracebacks are shared with software creators to empower the developers with the data and accreditation they deserve to improve software.',
      img: '@/assets/img/storyscript-solution.svg'
    }, {
      name: 'Runtime',
      content: 'Service-oriented architecture generated by Storyscript.<br>Your stories come alive in a robust, scalable enterprise-grade stack that combines  trusted, industry-standard products paving the way for zero-devops deployments.',
      img: '@/assets/img/runtime-solution.svg'
    }, {
      name: 'Dashboard',
      content: 'Powerful data for actionable insights.<br>Machine learning influenced metrics and application insights assist developer to make data-driven decisions.<br><br>',
      img: '@/assets/img/dash-solution.svg'
    }]
  }),
  methods: {
    stepName: function (step) {
      if (step < 1 || step > this.steps.length) return ' '
      return this.steps[step - 1].name
    },
    stepContent: function (step) {
      if (step < 1 || step > this.steps.length) return ' '
      return this.steps[step - 1].content
    },
    stepColor: (step, currentStep) => (step === currentStep ? '#03DAC5' : '#464769')
  }
}
</script>

<style lang="scss">
.vue-typer.dark {
  .vue-typer-caret-blink {
    background-color: #fff;
    // display: inline-block !important;
  }
  &, & span.typed {
    color: #fff !important;
    font-weight: bold;
  }
}
.is-lock-marged {
  max-width: 1440px;
  padding: 0 3rem !important;
}

.is-dots {
  margin-top: 4rem !important;
}

p.solution-content {
    margin: 2rem 0 !important;
    color: gray(500);
    font-weight: bold;
    b {
      color: gray(200);
    }
  }
</style>
<style lang="scss" scoped>
.solution {
  background-color: #0A0A0A !important;

  .step {
    min-height: 100vh;
  }

  h2 {
    color: #fff;
  }

  .separator {
    width: 1rem;
    height: .25rem;
    background: gray(500);
  }

  .rounded {
    width: 100%;
    height: 400px;
    border-radius: .5rem;
    // background: url('~@/assets/img/dashboard.svg');
    background-position: center;
    background-repeat: no-repeat;
    background-size: contain;
  }
}
</style>
