<template>
  <section class="section solution">
    <lock-room :steps="steps.length">
      <template slot-scope="{ step }">
        <div class="columns is-mobile is-gapless">
          <div class="column is-three-quarters text--left">
            <h2>{{ step > 1 ? 'Asyncy ' : '' }}<vue-typer
              :repeat="0"
              :text="stepName(step)"
              class="dark" /></h2>
            <div class="separator" />
            <p
              class="solution-content"
              v-html="stepContent(step)" />
            <div class="rounded">
              <solution-svg />
            </div>
          </div>
        </div>
      </template>
    </lock-room>
  </section>
</template>

<script>
import SolutionSvg from '@/components/Home/SolutionSvg'
import LockRoom from '@/components/LockRoom'

export default {
  name: 'SolutionLock',
  components: { LockRoom, SolutionSvg },
  data: () => ({
    steps: [{
      name: 'Meet Storyscript',
      content: 'The language for storytelling data that powers your application.<br>Storyscript strings together microservices, representing architecture as code. Fully-asynchronous, service-oriented programming that intuitively expresses data flow to rapidly develop applications in a production-grade environment.'
    }, {
      name: 'Hub',
      content: 'The developer marketplace to build, share and discover <b>microservices</b>.<br>Anonymous metrics and tracebacks are shared with software creators to empower the developers with the data and accreditation they deserve to improve software.'
    }, {
      name: 'Runtime',
      content: 'Service-oriented architecture generated by Storyscript.<br>Your stories come alive in a robust, scalable enterprise-grade stack that combines  trusted, industry-standard products paving the way for zero-devops deployments.'
    }, {
      name: 'Dashboard',
      content: 'Powerful data for actionable insights.<br>Machine learning influenced metrics and application insights assist developer to make data-driven decisions.'
    }]
  }),
  methods: {
    stepName: function (step) {
      if (step < 1 || step > this.steps.length) return ' '
      return this.steps[step - 1].name
    },
    stepContent: function (step) {
      if (step < 1 || step > this.steps.length) return ' '
      return this.steps[step - 1].content
    }
  }
}
</script>

<style lang="scss">
.vue-typer.dark {
  .vue-typer-caret-blink {
    background-color: #fff !important;
    display: inline-block !important;
  }
  &, & span.typed {
    color: #fff !important;
    font-weight: bold;
  }
}

p.solution-content {
    margin: 2rem 0 !important;
    color: gray(500);
    font-weight: bold;
    b {
      color: gray(200);
    }
  }
</style>
<style lang="scss" scoped>
.solution {
  background-color: #0A0A0A !important;

  h2 {
    color: #fff;
  }

  .separator {
    width: 1rem;
    height: .25rem;
    background: gray(500);
  }

  .rounded {
    width: 100%;
    height: 400px;
    border-radius: .5rem;
    // background: url('~@/assets/img/dashboard.svg');
    background-position: center;
    background-repeat: no-repeat;
    background-size: contain;
  }
}
</style>
