<template>
  <section class="solution-container">
    <solution-template
      v-for="(step, idx) of steps"
      :key="`solution-${idx}`"
      :idx="idx"
      :name="step.name"
      :content="step.content" />
  </section>
</template>

<script>
import SolutionTemplate from '@/components/SolutionTemplate'

export default {
  name: 'Solution',
  components: { SolutionTemplate },
  data: () => ({
    steps: [{
      name: 'Meet Storyscript',
      content: 'The language for storytelling data that powers your application.<br>Storyscript strings together microservices, representing architecture as code. Fully-asynchronous, service-oriented programming that intuitively expresses data flow to rapidly develop applications in a production-grade environment.'
    }, {
      name: 'Hub',
      content: 'The developer marketplace to build, share and discover <b>microservices</b>.<br>Anonymous metrics and tracebacks are shared with software creators to empower the developers with the data and accreditation they deserve to improve software.'
    }, {
      name: 'Runtime',
      content: 'Service-oriented architecture generated by Storyscript.<br>Your stories come alive in a robust, scalable enterprise-grade stack that combines  trusted, industry-standard products paving the way for zero-devops deployments.'
    }, {
      name: 'Dashboard',
      content: 'Powerful data for actionable insights.<br>Machine learning influenced metrics and application insights assist developer to make data-driven decisions.<br><br>'
    }]
  })
}
</script>
